### PR TITLE
Cart and wishlist

### PR DESCRIPTION
**Pull request by znjs**
### WishList
image
### Cart
image
image
image
### Success message
image

### CODE REVIEW

**Review by Tejs1 — APPROVED** [review]
wow good work

**Review by ScoobyDubeyDo — APPROVED** [review]
Looks good 👍

**Review by Tejs1 — APPROVED** [review]
add to cart and Wishlist icon in nav bar seems different in style, rest is good

**Comment by znjs** [comment]
> 

Yes i am using yellow as CTA so I have given a background yellow for cart and red default for wishlist

**Review by Tejs1 — COMMENTED** [review]
lgtm

**Pull request merged**
